/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

export declare const internalGroqTypeReferenceTo: unique symbol;

// Source: src/sanity/schema.json
export type Announcement = {
  _id: string;
  _type: "announcement";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  date?: string;
  body?: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "normal";
    listItem?: never;
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }>;
  link?: CtaLink;
  active?: boolean;
  expiresAt?: string;
};

export type CtaLink = {
  _type: "ctaLink";
  label?: string;
  href?: string;
};

export type SanityImageAssetReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
};

export type Event = {
  _id: string;
  _type: "event";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  slug?: Slug;
  date?: string;
  endDate?: string;
  location?: string;
  type?: "workshop" | "ctf" | "speaker" | "mentorship" | "other";
  summary?: string;
  body?: Array<
    | {
        children?: Array<{
          marks?: Array<string>;
          text?: string;
          _type: "span";
          _key: string;
        }>;
        style?: "normal";
        listItem?: "bullet";
        markDefs?: Array<{
          href?: string;
          _type: "link";
          _key: string;
        }>;
        level?: number;
        _type: "block";
        _key: string;
      }
    | {
        asset?: SanityImageAssetReference;
        media?: unknown;
        hotspot?: SanityImageHotspot;
        crop?: SanityImageCrop;
        alt?: string;
        _type: "image";
        _key: string;
      }
  >;
  image?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  };
  registrationUrl?: string;
  featured?: boolean;
};

export type SanityImageCrop = {
  _type: "sanity.imageCrop";
  top?: number;
  bottom?: number;
  left?: number;
  right?: number;
};

export type SanityImageHotspot = {
  _type: "sanity.imageHotspot";
  x?: number;
  y?: number;
  height?: number;
  width?: number;
};

export type Slug = {
  _type: "slug";
  current?: string;
  source?: string;
};

export type TeamMember = {
  _id: string;
  _type: "teamMember";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: string;
  role?: string;
  isFacultyAdvisor?: boolean;
  category?: "board" | "advisor" | "core" | "member";
  photo?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  };
  bio?: string;
  order?: number;
  socials?: Array<
    {
      _key: string;
    } & SocialLink
  >;
  slug?: Slug;
};

export type ContactInfo = {
  _id: string;
  _type: "contactInfo";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  heading?: string;
  intro?: string;
  channelsHeading?: string;
  channels?: Array<{
    label?: string;
    value?: string;
    href?: string;
    kind?: "email" | "instagram" | "linkedin" | "discord" | "other";
    _type: "channel";
    _key: string;
  }>;
  formHeading?: string;
};

export type AboutPage = {
  _id: string;
  _type: "aboutPage";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  heading?: string;
  intro?: string;
  missionTitle?: string;
  missionBody?: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "normal";
    listItem?: never;
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }>;
  whyTitle?: string;
  whyBody?: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "normal";
    listItem?: never;
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }>;
  valuesHeading?: string;
  values?: Array<{
    term?: string;
    def?: string;
    _type: "value";
    _key: string;
  }>;
  teamCtaText?: string;
};

export type HomePage = {
  _id: string;
  _type: "homePage";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  heroHeading?: string;
  heroBody?: string;
  heroPrimaryCta?: CtaLink;
  heroSecondaryCta?: CtaLink;
  offeringsHeading?: string;
  offerings?: Array<{
    title?: string;
    body?: string;
    _type: "offering";
    _key: string;
  }>;
  stats?: Array<
    {
      _key: string;
    } & StatItem
  >;
  closingCtaHeading?: string;
  closingCtaBody?: string;
  closingCta?: CtaLink;
};

export type SiteSettings = {
  _id: string;
  _type: "siteSettings";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  wordmarkSuffix?: string;
  headerCta?: CtaLink;
  footerTagline?: string;
  footerAffiliationLine?: string;
  socials?: Array<
    {
      _key: string;
    } & SocialLink
  >;
};

export type StatItem = {
  _type: "statItem";
  value?: number;
  suffix?: string;
  label?: string;
};

export type SocialLink = {
  _type: "socialLink";
  platform?: "email" | "instagram" | "linkedin" | "discord" | "github";
  url?: string;
};

export type SanityImagePaletteSwatch = {
  _type: "sanity.imagePaletteSwatch";
  background?: string;
  foreground?: string;
  population?: number;
  title?: string;
};

export type SanityImagePalette = {
  _type: "sanity.imagePalette";
  darkMuted?: SanityImagePaletteSwatch;
  lightVibrant?: SanityImagePaletteSwatch;
  darkVibrant?: SanityImagePaletteSwatch;
  vibrant?: SanityImagePaletteSwatch;
  dominant?: SanityImagePaletteSwatch;
  lightMuted?: SanityImagePaletteSwatch;
  muted?: SanityImagePaletteSwatch;
};

export type SanityImageDimensions = {
  _type: "sanity.imageDimensions";
  height?: number;
  width?: number;
  aspectRatio?: number;
};

export type SanityImageMetadata = {
  _type: "sanity.imageMetadata";
  location?: Geopoint;
  dimensions?: SanityImageDimensions;
  palette?: SanityImagePalette;
  lqip?: string;
  blurHash?: string;
  thumbHash?: string;
  hasAlpha?: boolean;
  isOpaque?: boolean;
};

export type SanityFileAsset = {
  _id: string;
  _type: "sanity.fileAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  source?: SanityAssetSourceData;
};

export type SanityAssetSourceData = {
  _type: "sanity.assetSourceData";
  name?: string;
  id?: string;
  url?: string;
};

export type SanityImageAsset = {
  _id: string;
  _type: "sanity.imageAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  metadata?: SanityImageMetadata;
  source?: SanityAssetSourceData;
};

export type Geopoint = {
  _type: "geopoint";
  lat?: number;
  lng?: number;
  alt?: number;
};

export type AllSanitySchemaTypes =
  | Announcement
  | CtaLink
  | SanityImageAssetReference
  | Event
  | SanityImageCrop
  | SanityImageHotspot
  | Slug
  | TeamMember
  | ContactInfo
  | AboutPage
  | HomePage
  | SiteSettings
  | StatItem
  | SocialLink
  | SanityImagePaletteSwatch
  | SanityImagePalette
  | SanityImageDimensions
  | SanityImageMetadata
  | SanityFileAsset
  | SanityAssetSourceData
  | SanityImageAsset
  | Geopoint;

// Source: src/sanity/queries.ts
// Variable: SITE_SETTINGS_QUERY
// Query: *[_type == "siteSettings"][0]{    wordmarkSuffix,    headerCta,    footerTagline,    footerAffiliationLine,    socials[]{ platform, url }  }
export type SITE_SETTINGS_QUERY_RESULT = {
  wordmarkSuffix: string | null;
  headerCta: CtaLink | null;
  footerTagline: string | null;
  footerAffiliationLine: string | null;
  socials: Array<{
    platform: "discord" | "email" | "github" | "instagram" | "linkedin" | null;
    url: string | null;
  }> | null;
} | null;

// Source: src/sanity/queries.ts
// Variable: HOME_QUERY
// Query: *[_type == "homePage"][0]{    heroHeading,    heroBody,    heroPrimaryCta,    heroSecondaryCta,    offeringsHeading,    offerings[]{ title, body },    stats[]{ value, suffix, label },    closingCtaHeading,    closingCtaBody,    closingCta  }
export type HOME_QUERY_RESULT = {
  heroHeading: string | null;
  heroBody: string | null;
  heroPrimaryCta: CtaLink | null;
  heroSecondaryCta: CtaLink | null;
  offeringsHeading: string | null;
  offerings: Array<{
    title: string | null;
    body: string | null;
  }> | null;
  stats: Array<{
    value: number | null;
    suffix: string | null;
    label: string | null;
  }> | null;
  closingCtaHeading: string | null;
  closingCtaBody: string | null;
  closingCta: CtaLink | null;
} | null;

// Source: src/sanity/queries.ts
// Variable: ABOUT_QUERY
// Query: *[_type == "aboutPage"][0]{    heading,    intro,    missionTitle,    missionBody,    whyTitle,    whyBody,    valuesHeading,    values[]{ term, def },    teamCtaText  }
export type ABOUT_QUERY_RESULT = {
  heading: string | null;
  intro: string | null;
  missionTitle: string | null;
  missionBody: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "normal";
    listItem?: never;
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }> | null;
  whyTitle: string | null;
  whyBody: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "normal";
    listItem?: never;
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }> | null;
  valuesHeading: string | null;
  values: Array<{
    term: string | null;
    def: string | null;
  }> | null;
  teamCtaText: string | null;
} | null;

// Source: src/sanity/queries.ts
// Variable: CONTACT_QUERY
// Query: *[_type == "contactInfo"][0]{    heading,    intro,    channelsHeading,    channels[]{ label, value, href, kind },    formHeading  }
export type CONTACT_QUERY_RESULT = {
  heading: string | null;
  intro: string | null;
  channelsHeading: string | null;
  channels: Array<{
    label: string | null;
    value: string | null;
    href: string | null;
    kind: "discord" | "email" | "instagram" | "linkedin" | "other" | null;
  }> | null;
  formHeading: string | null;
} | null;

// Source: src/sanity/queries.ts
// Variable: TEAM_QUERY
// Query: *[_type == "teamMember"] | order(isFacultyAdvisor desc, order asc, name asc){    _id,    name,    role,    isFacultyAdvisor,    category,    bio,    "photo": photo{..., "alt": alt},    socials[]{ platform, url }  }
export type TEAM_QUERY_RESULT = Array<{
  _id: string;
  name: string | null;
  role: string | null;
  isFacultyAdvisor: boolean | null;
  category: "advisor" | "board" | "core" | "member" | null;
  bio: string | null;
  photo: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt: string | null;
    _type: "image";
  } | null;
  socials: Array<{
    platform: "discord" | "email" | "github" | "instagram" | "linkedin" | null;
    url: string | null;
  }> | null;
}>;

// Source: src/sanity/queries.ts
// Variable: EVENTS_UPCOMING_QUERY
// Query: *[_type == "event" && coalesce(endDate, date) >= now()] | order(date asc){    _id,    title,    "slug": slug.current,    date,    endDate,    location,    type,    summary,    "image": image{..., "alt": alt},    registrationUrl,    featured  }
export type EVENTS_UPCOMING_QUERY_RESULT = Array<{
  _id: string;
  title: string | null;
  slug: string | null;
  date: string | null;
  endDate: string | null;
  location: string | null;
  type: "ctf" | "mentorship" | "other" | "speaker" | "workshop" | null;
  summary: string | null;
  image: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt: string | null;
    _type: "image";
  } | null;
  registrationUrl: string | null;
  featured: boolean | null;
}>;

// Source: src/sanity/queries.ts
// Variable: EVENTS_PAST_QUERY
// Query: *[_type == "event" && coalesce(endDate, date) < now()] | order(date desc)[0...12]{    _id,    title,    "slug": slug.current,    date,    endDate,    location,    type,    summary,    "image": image{..., "alt": alt},    registrationUrl,    featured  }
export type EVENTS_PAST_QUERY_RESULT = Array<{
  _id: string;
  title: string | null;
  slug: string | null;
  date: string | null;
  endDate: string | null;
  location: string | null;
  type: "ctf" | "mentorship" | "other" | "speaker" | "workshop" | null;
  summary: string | null;
  image: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt: string | null;
    _type: "image";
  } | null;
  registrationUrl: string | null;
  featured: boolean | null;
}>;

// Source: src/sanity/queries.ts
// Variable: ANNOUNCEMENTS_QUERY
// Query: *[_type == "announcement" && active == true    && (!defined(expiresAt) || expiresAt > now())] | order(date desc){    _id,    title,    body,    link  }
export type ANNOUNCEMENTS_QUERY_RESULT = Array<{
  _id: string;
  title: string | null;
  body: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "normal";
    listItem?: never;
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }> | null;
  link: CtaLink | null;
}>;

// Query TypeMap
declare global {
  interface SanityQueries {
    '\n  *[_type == "siteSettings"][0]{\n    wordmarkSuffix,\n    headerCta,\n    footerTagline,\n    footerAffiliationLine,\n    socials[]{ platform, url }\n  }\n': SITE_SETTINGS_QUERY_RESULT;
    '\n  *[_type == "homePage"][0]{\n    heroHeading,\n    heroBody,\n    heroPrimaryCta,\n    heroSecondaryCta,\n    offeringsHeading,\n    offerings[]{ title, body },\n    stats[]{ value, suffix, label },\n    closingCtaHeading,\n    closingCtaBody,\n    closingCta\n  }\n': HOME_QUERY_RESULT;
    '\n  *[_type == "aboutPage"][0]{\n    heading,\n    intro,\n    missionTitle,\n    missionBody,\n    whyTitle,\n    whyBody,\n    valuesHeading,\n    values[]{ term, def },\n    teamCtaText\n  }\n': ABOUT_QUERY_RESULT;
    '\n  *[_type == "contactInfo"][0]{\n    heading,\n    intro,\n    channelsHeading,\n    channels[]{ label, value, href, kind },\n    formHeading\n  }\n': CONTACT_QUERY_RESULT;
    '\n  *[_type == "teamMember"] | order(isFacultyAdvisor desc, order asc, name asc){\n    _id,\n    name,\n    role,\n    isFacultyAdvisor,\n    category,\n    bio,\n    "photo": photo{..., "alt": alt},\n    socials[]{ platform, url }\n  }\n': TEAM_QUERY_RESULT;
    '\n  *[_type == "event" && coalesce(endDate, date) >= now()] | order(date asc){\n    _id,\n    title,\n    "slug": slug.current,\n    date,\n    endDate,\n    location,\n    type,\n    summary,\n    "image": image{..., "alt": alt},\n    registrationUrl,\n    featured\n  }\n': EVENTS_UPCOMING_QUERY_RESULT;
    '\n  *[_type == "event" && coalesce(endDate, date) < now()] | order(date desc)[0...12]{\n    _id,\n    title,\n    "slug": slug.current,\n    date,\n    endDate,\n    location,\n    type,\n    summary,\n    "image": image{..., "alt": alt},\n    registrationUrl,\n    featured\n  }\n': EVENTS_PAST_QUERY_RESULT;
    '\n  *[_type == "announcement" && active == true\n    && (!defined(expiresAt) || expiresAt > now())] | order(date desc){\n    _id,\n    title,\n    body,\n    link\n  }\n': ANNOUNCEMENTS_QUERY_RESULT;
  }
}
// Lets @sanity/client releases that predate the global registry read it too
declare module "@sanity/client" {
  interface SanityQueries extends globalThis.SanityQueries {}
}
